[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "expect hill icon clarify copper eager brisk treat weather card girl wait ordinary census health flock journey turn random pepper consider rib slender talent"
